/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.blisswisdom.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CommentsUpdate service. Represents a row in the &quot;bw_CommentsUpdate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.blisswisdom.model.impl.CommentsUpdateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.blisswisdom.model.impl.CommentsUpdateImpl}.
 * </p>
 *
 * @author Danny
 * @see CommentsUpdate
 * @see org.blisswisdom.model.impl.CommentsUpdateImpl
 * @see org.blisswisdom.model.impl.CommentsUpdateModelImpl
 * @generated
 */
public interface CommentsUpdateModel extends BaseModel<CommentsUpdate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a comments update model instance should use the {@link CommentsUpdate} interface instead.
	 */

	/**
	 * Returns the primary key of this comments update.
	 *
	 * @return the primary key of this comments update
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this comments update.
	 *
	 * @param primaryKey the primary key of this comments update
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the comments update ID of this comments update.
	 *
	 * @return the comments update ID of this comments update
	 */
	public long getCommentsUpdateId();

	/**
	 * Sets the comments update ID of this comments update.
	 *
	 * @param commentsUpdateId the comments update ID of this comments update
	 */
	public void setCommentsUpdateId(long commentsUpdateId);

	/**
	 * Returns the petition ID of this comments update.
	 *
	 * @return the petition ID of this comments update
	 */
	public long getPetitionId();

	/**
	 * Sets the petition ID of this comments update.
	 *
	 * @param petitionId the petition ID of this comments update
	 */
	public void setPetitionId(long petitionId);

	/**
	 * Returns the user ID of this comments update.
	 *
	 * @return the user ID of this comments update
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this comments update.
	 *
	 * @param userId the user ID of this comments update
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this comments update.
	 *
	 * @return the user uuid of this comments update
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this comments update.
	 *
	 * @param userUuid the user uuid of this comments update
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this comments update.
	 *
	 * @return the user name of this comments update
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this comments update.
	 *
	 * @param userName the user name of this comments update
	 */
	public void setUserName(String userName);

	/**
	 * Returns the comments type of this comments update.
	 *
	 * @return the comments type of this comments update
	 */
	@AutoEscape
	public String getCommentsType();

	/**
	 * Sets the comments type of this comments update.
	 *
	 * @param commentsType the comments type of this comments update
	 */
	public void setCommentsType(String commentsType);

	/**
	 * Returns the comments content of this comments update.
	 *
	 * @return the comments content of this comments update
	 */
	@AutoEscape
	public String getCommentsContent();

	/**
	 * Sets the comments content of this comments update.
	 *
	 * @param commentsContent the comments content of this comments update
	 */
	public void setCommentsContent(String commentsContent);

	/**
	 * Returns the update time of this comments update.
	 *
	 * @return the update time of this comments update
	 */
	public Date getUpdateTime();

	/**
	 * Sets the update time of this comments update.
	 *
	 * @param updateTime the update time of this comments update
	 */
	public void setUpdateTime(Date updateTime);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CommentsUpdate commentsUpdate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CommentsUpdate> toCacheModel();

	@Override
	public CommentsUpdate toEscapedModel();

	@Override
	public CommentsUpdate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}